# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MTbibdZwFXZ3qGAj1d7VlmttUtp3COI7
"""

#This is chat bot

!pip install newspaper3k

pip install nltk

#import libraries

from newspaper import Article
import random
import string
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import warnings

warnings.filterwarnings('ignore')

#Download punkt pacakge
nltk.download('punkt',quiet=True)

#Get the article
article=Article("https://www.geeksforgeeks.org/python-programming-language/")
article.download()
article.parse()
article.nlp()
corpus=article.text

#print the article test
print(corpus)

#Tokenization
text=corpus
sentence_list=nltk.sent_tokenize(text)

#Print list of sentences
print(sentence_list)

def greeting_response(text):
  text=text.lower()
  import random

  #Bot greeting response
  bot_greetings=['howly','hi','hello','hola']
  #user greetings
  user_greetings=['hi','hey','hola','wassup']

  for word in text.split():
    if word in user_greetings:
      return random.choice(bot_greetings)

def bot_response(user_input):
 user_input=user_input.lower()
 sentence_list.append(user_input)
 bot_response=''
 cm= CountVectorizer().fit_transform(sentence_list)
 similarity_scores=cosine_similarity(cm[-1],cm)
 similarity_scores_list=similarity_scores_flatten()
 index=index_sort(similarity_scores_list)
 index=index[1:]
 response_flag=0

 j=0
 for i in range (len(index)):
   if similarity_scores_list[index[i]]>0.0:
     bot_response=bot_response+''+sentence_list[index[i]]
     response_flag=1
     j=j+1
   if j>2:
     break

 if response_flag==0:
   bot_response=bot_response+''+"I apologize.i dont understand"

 sentence_list_remove(user_input)

 return bot_response

print('Doc bot: I am Doctor bot and I will answer your questionries .I you want exit plz type Bye')

exit_list=['seeyou','bye','quit','break']

while (True):
  user_input=input()
  if user_input.lower() in exit_list:
    print("Chat bot Hiru: chat with you later")
    break
  else:
    if greeting_response(user_input)!=None:
      print("Chat bot Hiru :" +greeting_response(user_input))
    else:
      print("Chat bot Hiru :" +bot_response(user_input))

